#!/usr/bin/env bash
# Branch protection is API state, not a file. Shipping the checks without the enforcement would
# contradict this process's own maxim — an instruction is a request, a check is a guarantee — at
# the moment of installation.
#
# Generated by `acb init`. Re-run it after changing .acb.json's components, so the required check
# names still match the workflow's job names; `acb status` reports when they drift.
set -euo pipefail
cd "$(dirname "$0")/.."
: "${GITHUB_REPOSITORY:?set GITHUB_REPOSITORY=owner/name}"

# Check the call SUCCEEDED before using its output. `gh api --jq` on an error response prints the
# error body, so `|| true` here would assign a JSON blob to $existing and build a nonsense URL
# from it — which is exactly what happened the first time this ran.
if ! listing="$(gh api "repos/$GITHUB_REPOSITORY/rulesets" 2>&1)"; then
  echo "✗ cannot read rulesets for $GITHUB_REPOSITORY:" >&2
  echo "$listing" | sed 's/^/    /' >&2
  case "$listing" in
    *"Upgrade to GitHub Pro"*)
      echo >&2
      echo "  Repository rulesets on a PRIVATE repository require GitHub Pro, Team or Enterprise." >&2
      echo "  They are free on a public repository. Either make this repository public, upgrade," >&2
      echo "  or accept that the checks run without being required — which means they are" >&2
      echo "  advisory, not gates. Decide deliberately; do not leave it unnoticed." >&2
      ;;
  esac
  exit 1
fi

existing="$(jq -r '.[] | select(.name=="Protect main") | .id' <<<"$listing")"
if [[ -n "$existing" ]]; then
  gh api --method PUT "repos/$GITHUB_REPOSITORY/rulesets/$existing" --input .github/ruleset.json >/dev/null
  echo "✓ ruleset updated (id $existing)"
else
  gh api --method POST "repos/$GITHUB_REPOSITORY/rulesets" --input .github/ruleset.json >/dev/null
  echo "✓ ruleset created"
fi
echo "  verify: gh api repos/$GITHUB_REPOSITORY/rulesets"
