#!/usr/bin/env bash
# Branch protection is API state, not a file. Shipping the checks without the enforcement would
# contradict this process's own maxim — an instruction is a request, a check is a guarantee — at
# the moment of installation.
#
# Generated by `acb init`, and THIS REPOSITORY'S OWN THEREAFTER. Do not re-run `acb init` to
# refresh it: init overwrites CLAUDE.md, every component's verify.sh, ci.yml and this file with
# skeletons, which would destroy an adopted repository. Edit .github/ruleset.json by hand and run
# this script.
#
# Usage:
#   GITHUB_REPOSITORY=owner/name ./scripts/apply-ruleset.sh          # show the diff, apply nothing
#   GITHUB_REPOSITORY=owner/name ./scripts/apply-ruleset.sh --apply  # apply it
set -euo pipefail
cd "$(dirname "$0")/.."
: "${GITHUB_REPOSITORY:?set GITHUB_REPOSITORY=owner/name}"

apply=0
case "${1:-}" in
  --apply) apply=1 ;;
  "") ;;
  *) echo "usage: [--apply]" >&2; exit 2 ;;
esac

# Preflight the document before any call that could mutate anything. A partial `acb init`, a bad
# merge resolution or a truncated write otherwise surfaces as an HTTP 422 from inside gh, after
# the operator has already been told the listing succeeded.
if [[ ! -s .github/ruleset.json ]] || ! jq -e . .github/ruleset.json >/dev/null 2>&1; then
  echo "✗ .github/ruleset.json is missing, empty or not valid JSON." >&2
  exit 1
fi

# stderr goes to its own file, NOT into $listing. `gh` writes upgrade notices and token-scope
# warnings to stderr, and folding those into the capture corrupts the JSON on the SUCCESS path —
# jq then dies with "Invalid numeric literal" and `set -e` aborts before anything is applied,
# leaving the operator with a parse error and no idea the ruleset was untouched.
err="$(mktemp)"; trap 'rm -f "$err"' EXIT
if ! listing="$(gh api --paginate "repos/$GITHUB_REPOSITORY/rulesets?includes_parents=false" 2>"$err")"; then
  echo "✗ cannot read rulesets for $GITHUB_REPOSITORY:" >&2
  sed 's/^/    /' "$err" >&2
  case "$(cat "$err")" in
    *"Upgrade to GitHub Pro"*)
      echo >&2
      echo "  Repository rulesets on a PRIVATE repository require GitHub Pro, Team or Enterprise." >&2
      echo "  They are free on a public repository. Either make this repository public, upgrade," >&2
      echo "  or accept that the checks run without being required — which means they are" >&2
      echo "  advisory, not gates. Decide deliberately; do not leave it unnoticed." >&2
      ;;
  esac
  exit 1
fi

# `includes_parents=false` above, and Repository-scoped here as belt and braces: the endpoint
# otherwise returns organization and enterprise rulesets too, and an org ruleset that happens to
# share this name would hand back an id that does not belong to this repository.
# A `while read` loop, not `mapfile`: mapfile is bash 4+ and macOS ships 3.2, which this toolkit
# targets. `$(...)` strips the trailing newline, so a single id yields a one-element list.
ids=""; n=0
while IFS= read -r line; do
  [[ -n "$line" ]] || continue
  ids="${ids}${ids:+ }${line}"; n=$((n + 1))
done < <(jq -r '.[] | select(.name=="Protect main" and (.source_type // "Repository")=="Repository") | .id' <<<"$listing")
if [[ "$n" -gt 1 ]]; then
  echo "✗ $n repository rulesets are named 'Protect main' (ids: $ids)." >&2
  echo "  Refusing to guess which one to overwrite. Delete the duplicates first." >&2
  exit 1
fi
existing="$ids"

# The diff is the review, and it is the default. docs/sdlc-local.md says the LIVE ruleset is the
# reference and to find out why the two disagree before overwriting — a tool with no way to look
# makes that an instruction rather than a check.
if [[ -n "$existing" ]]; then
  echo "==> diff: live (left) vs .github/ruleset.json (right)"
  if diff -u \
      <(gh api "repos/$GITHUB_REPOSITORY/rulesets/$existing" 2>/dev/null \
          | jq -S '{name,target,enforcement,conditions,bypass_actors,rules}') \
      <(jq -S '{name,target,enforcement,conditions,bypass_actors,rules}' .github/ruleset.json); then
    echo "    no difference — the document already describes the live ruleset."
  fi
else
  echo "==> no ruleset named 'Protect main' exists yet; this would CREATE one."
fi

if [[ "$apply" -eq 0 ]]; then
  echo
  echo "Nothing applied. Re-run with --apply to write the document above to $GITHUB_REPOSITORY."
  exit 0
fi

if [[ -n "$existing" ]]; then
  gh api --method PUT "repos/$GITHUB_REPOSITORY/rulesets/$existing" --input .github/ruleset.json >/dev/null
  echo "✓ ruleset updated (id $existing)"
else
  gh api --method POST "repos/$GITHUB_REPOSITORY/rulesets" --input .github/ruleset.json >/dev/null
  echo "✓ ruleset created"
fi
echo "  verify: gh api repos/$GITHUB_REPOSITORY/rulesets"
