#!/usr/bin/env bash
# One command to open a git worktree that can actually run the app.
#
# A bare `git worktree add` produces a tree that cannot run anything: node_modules is absent, and
# every gitignored file — `.env.shared`, `frontend/.env.local`, and `.claude/settings.local.json`
# (the permission allowlist, whose absence makes a fresh Claude Code session re-prompt for
# permissions it already has) — is missing. This creates the worktree, allocates a stack slot so
# its ports do not collide with any other tree, supplies those files, and installs dependencies.
#
# Usage:  scripts/worktree-new.sh <slug> [branch]
#   slug       directory under .claude/worktrees/ (letters, digits, dot, dash, underscore)
#   branch     branch to create (default: feat/<slug>)
#   SLOT_MAX   highest slot to hand out (default 3 — bounded by the frontend origins registered
#              in Auth0, whose allowed-origins list is exact-match; see README.md)
#
# Sourcing with WORKTREE_NEW_LIB=1 defines the helpers and runs nothing, which is how
# scripts/tests/worktree-new.test.sh exercises the slot arithmetic without touching git.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SLOT_MAX="${SLOT_MAX:-3}"

# Port bases, one per published service. Slot N gets base + N*SLOT_STEP. These four numbers and
# the step ARE the slot table in README.md; backend/src/config.ts repeats them to warn when a
# worktree's .env drifts from them.
SLOT_STEP=10
BASE_BACKEND=8000
BASE_FRONTEND=5173
BASE_PG=5432
BASE_REDIS=6379

port_for() { echo $(($1 + $2 * SLOT_STEP)); }

# slot_of — read a .env on stdin, print the slot it claims (nothing if it claims none).
#
# `q` inside sed rather than `| head -1`: under `set -o pipefail` a hand-edited .env with two
# STACK_SLOT lines can leave sed killed by SIGPIPE (141), which becomes the pipeline's status and,
# since this is the last command in used_slots' loop body, kills that subshell mid-iteration.
# Every remaining worktree's claim is then dropped and free_slot hands out a slot that is already
# taken — the one invariant this whole design exists to hold. Same hazard scripts/check-sdlc-sync.sh
# documents for `grep -q` on a large diff.
slot_of() { sed -nE '/^STACK_SLOT=/{s/^STACK_SLOT=([0-9]+).*/\1/p;q;}'; }

# free_slot <used-slot>... -> the lowest slot in 1..SLOT_MAX that is not in use.
# Slot 0 is reserved for the main checkout, whose ports the README and every curl example name.
free_slot() {
  local candidate used
  for ((candidate = 1; candidate <= SLOT_MAX; candidate++)); do
    for used in "$@"; do
      [[ "$used" == "$candidate" ]] && continue 2
    done
    echo "$candidate"
    return 0
  done
  {
    echo "no free stack slot: 1..${SLOT_MAX} are all in use."
    echo "Remove a worktree, or raise SLOT_MAX — but register the extra frontend origin in the"
    echo "Auth0 SPA's allowed callback / logout / web origins first, or login will fail there."
  } >&2
  return 1
}

# project_name <slot> <slug> -> a Compose project name. Compose accepts lowercase alphanumerics,
# dash and underscore only; anything else becomes a dash.
project_name() {
  local slot="$1" slug
  slug="$(printf '%s' "$2" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_-]+/-/g; s/^-+|-+$//g')"
  printf 'llmce-slot%s-%s\n' "$slot" "$slug"
}

# stack_env <slot> <project-name> -> the worktree's .env, on stdout.
#
# Every variable backend/src/config.ts's stackSlotWarnings() reads must appear here and agree with
# the slot, or the first `npm run dev` in a brand-new worktree greets you with warnings about the
# tooling's own output.
stack_env() {
  local slot="$1" project="$2" backend frontend pg redis
  backend="$(port_for "$BASE_BACKEND" "$slot")"
  frontend="$(port_for "$BASE_FRONTEND" "$slot")"
  pg="$(port_for "$BASE_PG" "$slot")"
  redis="$(port_for "$BASE_REDIS" "$slot")"
  cat <<EOF
# Generated by scripts/worktree-new.sh — this worktree's stack identity. Do not commit.
# Settings shared with every other worktree live in .env.shared, a symlink to the main
# checkout's copy. See "Parallel worktrees" in README.md for the slot table.
STACK_SLOT=${slot}
COMPOSE_PROJECT_NAME=${project}

# Published host ports. Container-internal ports never change.
BACKEND_PORT=${backend}
FRONTEND_PORT=${frontend}
PG_PORT=${pg}
REDIS_PORT=${redis}

# CORS origin for this worktree's frontend — must match FRONTEND_PORT, and must be one of the
# origins registered in the Auth0 SPA, or login fails here with no useful error.
FRONTEND_ORIGIN=http://localhost:${frontend}

# What a host-run backend (\`npm run dev\`) listens on. Compose pins the container to 8000 at
# every slot and publishes it on BACKEND_PORT instead.
PORT=${backend}

# Per-slot tag: image tags are daemon-wide, so a shared one would let this worktree's edits to
# backend/sandbox-image/ change what every other worktree's backend EXECUTES.
SANDBOX_IMAGE=llm-sandbox:slot${slot}

# Host-run connection strings. Compose overrides both with compose-network service names.
DATABASE_URL=postgres://app:app@localhost:${pg}/app
REDIS_URL=redis://localhost:${redis}
EOF
}

# frontend_env <slot> <auth0-lines> -> the worktree's frontend/.env.local, on stdout.
#
# The Auth0 values are COPIED rather than symlinked: `frontend/` is the frontend image's Docker
# build context, and a symlink pointing outside it does not survive `COPY . .`, so the
# containerized frontend would lose its configuration. They are public SPA values, not secrets.
frontend_env() {
  local slot="$1" auth0="$2"
  # printf '%s\n' and not `echo "$auth0"; ...`: appending to a value with no trailing newline
  # splices VITE_DEV_PORT onto the end of the last Auth0 value, which breaks login AND leaves the
  # port unset — so the worktree binds slot 0's origin instead of its own.
  [[ -n "$auth0" ]] && printf '%s\n' "$auth0"
  printf 'VITE_DEV_PORT=%s\n' "$(port_for "$BASE_FRONTEND" "$slot")"
  printf 'VITE_API_BASE=http://localhost:%s\n' "$(port_for "$BASE_BACKEND" "$slot")"
}

# used_slots -> every slot currently claimed, one per line: the main checkout plus each registered
# worktree. A tree with no .env yet claims nothing, which is correct — it cannot run a stack.
used_slots() {
  local dir
  {
    printf '%s\n' "$ROOT"
    # Strip the prefix rather than taking field 2: a checkout path containing a space would be
    # truncated at the space, so that tree's claim would be missed and its slot handed out twice.
    git -C "$ROOT" worktree list --porcelain | sed -n 's/^worktree //p'
  } | sort -u | while read -r dir; do
    [[ -f "$dir/.env" ]] || continue
    slot_of <"$dir/.env"
  done
}

# State the EXIT trap needs. Global because the trap runs after main() returns, where a `local`
# is gone and `set -u` would kill the handler before it could release the lock.
LOCK_DIR=""
WT_DIR=""
WT_BRANCH=""
WT_SLOT=""
WT_CREATED=""

on_exit() {
  local code=$?
  [[ -n "$LOCK_DIR" ]] && rmdir "$LOCK_DIR" 2>/dev/null
  [[ $code -eq 0 || -z "$WT_CREATED" ]] && return $code
  {
    echo
    echo "✗ failed after the worktree was created. It is still on disk, holding slot ${WT_SLOT}."
    echo "  Retry the install:  (cd $WT_DIR/backend && npm ci) && (cd $WT_DIR/frontend && npm ci)"
    echo "  Or remove it:       git -C $ROOT worktree remove --force $WT_DIR && git -C $ROOT branch -D $WT_BRANCH"
  } >&2
  return $code
}

main() {
  local slug="${1:-}" branch="${2:-}"
  # No slashes in the SLUG: it names the directory, and the symlink targets below are literal
  # `../..` chains, correct only for a single level under .claude/worktrees/. The BRANCH is a
  # separate argument precisely so `fix/…`, `chore/…` and `docs/…` are reachable — the slug's
  # own restriction must not dictate the branch namespace.
  if [[ ! "$slug" =~ ^[A-Za-z0-9._-]+$ ]]; then
    {
      echo "usage: scripts/worktree-new.sh <slug> [branch]"
      echo "  slug    directory under .claude/worktrees/ (letters, digits, dot, dash, underscore)"
      echo "  branch  branch to create (default: feat/<slug>)"
    } >&2
    exit 2
  fi
  branch="${branch:-feat/$slug}"
  # The slug regex admits plenty of strings git will not accept as a ref — `a..b`, `name.lock`,
  # a leading or trailing dot. Ask git rather than reimplementing its rules, and ask now: without
  # this the failure lands inside `git worktree add`, after the fetch and after this script has
  # already reported which slot it picked.
  if ! git check-ref-format --branch "$branch" >/dev/null 2>&1; then
    echo "✗ '$branch' is not a valid git branch name." >&2
    exit 2
  fi

  # Run from the main checkout only. In a linked worktree `.git` is a file, not a directory — and
  # creating a worktree from inside one would nest .claude/worktrees/ inside itself.
  if [[ ! -d "$ROOT/.git" ]]; then
    echo "✗ run this from the main checkout, not from a worktree." >&2
    exit 1
  fi

  local dir="$ROOT/.claude/worktrees/$slug"
  if [[ -e "$dir" ]]; then
    echo "✗ $dir already exists." >&2
    exit 1
  fi
  # Pre-flight, like the $dir check: otherwise `git worktree add -b` aborts AFTER the fetch and
  # surfaces git's error instead of this one.
  if git -C "$ROOT" show-ref --verify --quiet "refs/heads/$branch"; then
    echo "✗ branch '$branch' already exists. Pass a different one: worktree-new.sh $slug <branch>" >&2
    exit 1
  fi

  # Reading the claims and writing this worktree's own is check-then-act, and two invocations at
  # once — not far-fetched when the whole point is running several sessions in parallel — can both
  # see slot 1 free and both take it, colliding on every port and the sandbox image tag. `mkdir`
  # is atomic on every filesystem that matters, so it is the mutex. Held across the git work too,
  # because the claim is not durable until `.env` exists.
  LOCK_DIR="$ROOT/.claude/worktrees/.worktree-new.lock"
  mkdir -p "$ROOT/.claude/worktrees"
  if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    echo "✗ another worktree-new.sh is running (lock: $LOCK_DIR)." >&2
    echo "  If that is stale — no other run in flight — remove it: rmdir $LOCK_DIR" >&2
    exit 1
  fi
  # ONE exit handler for both jobs — a second `trap … EXIT` would silently replace this one.
  # Its state is GLOBAL, not `local`: an EXIT trap fires after main() has returned, where a local
  # is already out of scope and `set -u` would abort the handler itself.
  trap on_exit EXIT
  WT_DIR="$dir"
  WT_BRANCH="$branch"

  local slot project
  slot="$(free_slot $(used_slots))"
  project="$(project_name "$slot" "$slug")"
  WT_SLOT="$slot"

  echo "==> slot ${slot} — frontend http://localhost:$(port_for "$BASE_FRONTEND" "$slot"), backend :$(port_for "$BASE_BACKEND" "$slot")"

  git -C "$ROOT" fetch origin
  git -C "$ROOT" worktree add -b "$branch" "$dir" origin/main
  # From here the worktree and branch exist on disk, so a later failure — an npm ci that hits a
  # registry hiccup is the likely one — leaves both behind, with the generated .env making
  # used_slots count the slot as taken forever while a plain retry dies on "already exists".
  # Nothing is removed automatically: the tree may be worth keeping and re-running `npm ci` in.
  WT_CREATED=1

  # Gitignored files a worktree does not inherit. These two are symlinked rather than copied so
  # the API key and the permission allowlist each keep exactly one source of truth. Relative
  # targets — an absolute one would break if the checkout were ever moved. `.claude/worktrees/` is
  # two levels below the root, so $dir needs ../../.. and a file one level inside it needs
  # ../../../.. to reach the root.
  # Collected rather than printed inline: they belong AFTER the npm ci output, next to the ✓, or
  # nobody sees them. `blockers` mean the worktree genuinely cannot run; `notes` are things that
  # work but are worth knowing. Keeping them apart matters — filing a working setup under "will
  # not run" is how a warning stops being read.
  local -a blockers=() notes=()

  # A checkout that has not split its env yet is a supported layout (README, and the
  # `required: false` on docker-compose's .env.shared entry), so fall back to the root `.env` as
  # the shared half rather than handing over a worktree with no API key. The ordering makes this
  # safe: Compose reads .env.shared first and this worktree's .env second, dotenv reads .env
  # first — either way the slot's own values win over the fat file's slot-0 ones.
  if [[ -f "$ROOT/.env.shared" ]]; then
    ln -sfn "../../../.env.shared" "$dir/.env.shared"
  elif [[ -f "$ROOT/.env" ]]; then
    ln -sfn "../../../.env" "$dir/.env.shared"
    notes+=("the main checkout has no .env.shared, so .env.shared here points at its root .env
    instead. That works — the slot values in this worktree's own .env still win — but splitting
    the env (cp .env.shared.example .env.shared, move the shared values across) is tidier.")
  else
    blockers+=("no .env.shared and no .env in the main checkout, so this worktree has NO
    ANTHROPIC_API_KEY, no OIDC_* config and no sandbox limits — the generated .env carries slot
    identity only. Create one (cp .env.shared.example .env.shared), then:
      ln -s ../../../.env.shared $dir/.env.shared")
  fi

  [[ -f "$ROOT/.claude/settings.local.json" ]] &&
    ln -sfn "../../../../.claude/settings.local.json" "$dir/.claude/settings.local.json"

  stack_env "$slot" "$project" >"$dir/.env"

  local auth0=""
  if [[ -f "$ROOT/frontend/.env.local" ]]; then
    # `|| true`: grep exits 1 on no match, and under `set -e` that would abort here — AFTER the
    # worktree and branch exist, leaving a half-built tree behind.
    auth0="$(grep -E '^VITE_AUTH0_' "$ROOT/frontend/.env.local" || true)"
  fi
  if [[ -z "$auth0" ]]; then
    blockers+=("no VITE_AUTH0_* values found in the main checkout's frontend/.env.local, so the SPA
    will start with an undefined Auth0 domain and client id and login will fail at runtime with
    no diagnostic. Fill in $ROOT/frontend/.env.local, then copy those three lines into
    $dir/frontend/.env.local")
  fi
  frontend_env "$slot" "$auth0" >"$dir/frontend/.env.local"

  (cd "$dir/backend" && npm ci)
  (cd "$dir/frontend" && npm ci)

  echo
  echo "✓ worktree ready: $dir"
  echo "  cd $dir && docker compose up --build"
  echo "  then open http://localhost:$(port_for "$BASE_FRONTEND" "$slot")"

  local item
  if ((${#blockers[@]} > 0)); then
    {
      echo
      echo "⚠ but it will NOT run yet:"
      for item in "${blockers[@]}"; do echo "  - $item"; done
    } >&2
  fi
  if ((${#notes[@]} > 0)); then
    {
      echo
      echo "note:"
      for item in "${notes[@]}"; do echo "  - $item"; done
    } >&2
  fi
}

if [[ "${WORKTREE_NEW_LIB:-}" != "1" ]]; then
  main "$@"
fi
