#!/usr/bin/env bash
# One command to open a git worktree that can actually run the app.
#
# A bare `git worktree add` produces a tree that cannot run anything: node_modules is absent, and
# every gitignored file — `.env.shared`, `frontend/.env.local`, and `.claude/settings.local.json`
# (the permission allowlist, whose absence makes a fresh Claude Code session re-prompt for
# permissions it already has) — is missing. This creates the worktree, allocates a stack slot so
# its ports do not collide with any other tree, supplies those files, and installs dependencies.
#
# Usage:  scripts/worktree-new.sh <slug>
#   SLOT_MAX   highest slot to hand out (default 3 — bounded by the frontend origins registered
#              in Auth0, whose allowed-origins list is exact-match; see README.md)
#
# Sourcing with WORKTREE_NEW_LIB=1 defines the helpers and runs nothing, which is how
# scripts/tests/worktree-new.test.sh exercises the slot arithmetic without touching git.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SLOT_MAX="${SLOT_MAX:-3}"

# Port bases, one per published service. Slot N gets base + N*SLOT_STEP. These four numbers and
# the step ARE the slot table in README.md; backend/src/config.ts repeats them to warn when a
# worktree's .env drifts from them.
SLOT_STEP=10
BASE_BACKEND=8000
BASE_FRONTEND=5173
BASE_PG=5432
BASE_REDIS=6379

port_for() { echo $(($1 + $2 * SLOT_STEP)); }

# slot_of — read a .env on stdin, print the slot it claims (nothing if it claims none).
#
# `q` inside sed rather than `| head -1`: under `set -o pipefail` a hand-edited .env with two
# STACK_SLOT lines can leave sed killed by SIGPIPE (141), which becomes the pipeline's status and,
# since this is the last command in used_slots' loop body, kills that subshell mid-iteration.
# Every remaining worktree's claim is then dropped and free_slot hands out a slot that is already
# taken — the one invariant this whole design exists to hold. Same hazard scripts/check-sdlc-sync.sh
# documents for `grep -q` on a large diff.
slot_of() { sed -nE '/^STACK_SLOT=/{s/^STACK_SLOT=([0-9]+).*/\1/p;q;}'; }

# free_slot <used-slot>... -> the lowest slot in 1..SLOT_MAX that is not in use.
# Slot 0 is reserved for the main checkout, whose ports the README and every curl example name.
free_slot() {
  local candidate used
  for ((candidate = 1; candidate <= SLOT_MAX; candidate++)); do
    for used in "$@"; do
      [[ "$used" == "$candidate" ]] && continue 2
    done
    echo "$candidate"
    return 0
  done
  {
    echo "no free stack slot: 1..${SLOT_MAX} are all in use."
    echo "Remove a worktree, or raise SLOT_MAX — but register the extra frontend origin in the"
    echo "Auth0 SPA's allowed callback / logout / web origins first, or login will fail there."
  } >&2
  return 1
}

# project_name <slot> <slug> -> a Compose project name. Compose accepts lowercase alphanumerics,
# dash and underscore only; anything else becomes a dash.
project_name() {
  local slot="$1" slug
  slug="$(printf '%s' "$2" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_-]+/-/g; s/^-+|-+$//g')"
  printf 'llmce-slot%s-%s\n' "$slot" "$slug"
}

# stack_env <slot> <project-name> -> the worktree's .env, on stdout.
#
# Every variable backend/src/config.ts's stackSlotWarnings() reads must appear here and agree with
# the slot, or the first `npm run dev` in a brand-new worktree greets you with warnings about the
# tooling's own output.
stack_env() {
  local slot="$1" project="$2" backend frontend pg redis
  backend="$(port_for "$BASE_BACKEND" "$slot")"
  frontend="$(port_for "$BASE_FRONTEND" "$slot")"
  pg="$(port_for "$BASE_PG" "$slot")"
  redis="$(port_for "$BASE_REDIS" "$slot")"
  cat <<EOF
# Generated by scripts/worktree-new.sh — this worktree's stack identity. Do not commit.
# Settings shared with every other worktree live in .env.shared, a symlink to the main
# checkout's copy. See "Parallel worktrees" in README.md for the slot table.
STACK_SLOT=${slot}
COMPOSE_PROJECT_NAME=${project}

# Published host ports. Container-internal ports never change.
BACKEND_PORT=${backend}
FRONTEND_PORT=${frontend}
PG_PORT=${pg}
REDIS_PORT=${redis}

# CORS origin for this worktree's frontend — must match FRONTEND_PORT, and must be one of the
# origins registered in the Auth0 SPA, or login fails here with no useful error.
FRONTEND_ORIGIN=http://localhost:${frontend}

# What a host-run backend (\`npm run dev\`) listens on. Compose pins the container to 8000 at
# every slot and publishes it on BACKEND_PORT instead.
PORT=${backend}

# Per-slot tag: image tags are daemon-wide, so a shared one would let this worktree's edits to
# backend/sandbox-image/ change what every other worktree's backend EXECUTES.
SANDBOX_IMAGE=llm-sandbox:slot${slot}

# Host-run connection strings. Compose overrides both with compose-network service names.
DATABASE_URL=postgres://app:app@localhost:${pg}/app
REDIS_URL=redis://localhost:${redis}
EOF
}

# frontend_env <slot> <auth0-lines> -> the worktree's frontend/.env.local, on stdout.
#
# The Auth0 values are COPIED rather than symlinked: `frontend/` is the frontend image's Docker
# build context, and a symlink pointing outside it does not survive `COPY . .`, so the
# containerized frontend would lose its configuration. They are public SPA values, not secrets.
frontend_env() {
  local slot="$1" auth0="$2"
  # printf '%s\n' and not `echo "$auth0"; ...`: appending to a value with no trailing newline
  # splices VITE_DEV_PORT onto the end of the last Auth0 value, which breaks login AND leaves the
  # port unset — so the worktree binds slot 0's origin instead of its own.
  [[ -n "$auth0" ]] && printf '%s\n' "$auth0"
  printf 'VITE_DEV_PORT=%s\n' "$(port_for "$BASE_FRONTEND" "$slot")"
  printf 'VITE_API_BASE=http://localhost:%s\n' "$(port_for "$BASE_BACKEND" "$slot")"
}

# used_slots -> every slot currently claimed, one per line: the main checkout plus each registered
# worktree. A tree with no .env yet claims nothing, which is correct — it cannot run a stack.
used_slots() {
  local dir
  {
    printf '%s\n' "$ROOT"
    # Strip the prefix rather than taking field 2: a checkout path containing a space would be
    # truncated at the space, so that tree's claim would be missed and its slot handed out twice.
    git -C "$ROOT" worktree list --porcelain | sed -n 's/^worktree //p'
  } | sort -u | while read -r dir; do
    [[ -f "$dir/.env" ]] || continue
    slot_of <"$dir/.env"
  done
}

main() {
  local slug="${1:-}" branch="${2:-}"
  # No slashes in the SLUG: it names the directory, and the symlink targets below are literal
  # `../..` chains, correct only for a single level under .claude/worktrees/. The BRANCH is a
  # separate argument precisely so `fix/…`, `chore/…` and `docs/…` are reachable — the slug's
  # own restriction must not dictate the branch namespace.
  if [[ ! "$slug" =~ ^[A-Za-z0-9._-]+$ ]]; then
    {
      echo "usage: scripts/worktree-new.sh <slug> [branch]"
      echo "  slug    directory under .claude/worktrees/ (letters, digits, dot, dash, underscore)"
      echo "  branch  branch to create (default: feat/<slug>)"
    } >&2
    exit 2
  fi
  branch="${branch:-feat/$slug}"

  # Run from the main checkout only. In a linked worktree `.git` is a file, not a directory — and
  # creating a worktree from inside one would nest .claude/worktrees/ inside itself.
  if [[ ! -d "$ROOT/.git" ]]; then
    echo "✗ run this from the main checkout, not from a worktree." >&2
    exit 1
  fi

  local dir="$ROOT/.claude/worktrees/$slug"
  if [[ -e "$dir" ]]; then
    echo "✗ $dir already exists." >&2
    exit 1
  fi
  # Pre-flight, like the $dir check: otherwise `git worktree add -b` aborts AFTER the fetch and
  # surfaces git's error instead of this one.
  if git -C "$ROOT" show-ref --verify --quiet "refs/heads/$branch"; then
    echo "✗ branch '$branch' already exists. Pass a different one: worktree-new.sh $slug <branch>" >&2
    exit 1
  fi

  local slot project
  slot="$(free_slot $(used_slots))"
  project="$(project_name "$slot" "$slug")"

  echo "==> slot ${slot} — frontend http://localhost:$(port_for "$BASE_FRONTEND" "$slot"), backend :$(port_for "$BASE_BACKEND" "$slot")"

  git -C "$ROOT" fetch origin
  git -C "$ROOT" worktree add -b "$branch" "$dir" origin/main

  # From here the worktree and branch exist on disk. Anything that fails later — an npm ci that
  # hits a registry hiccup is the likely one — would otherwise abort under `set -e` leaving both
  # behind, and the generated .env makes used_slots count the slot as taken forever while a plain
  # retry dies on "$dir already exists". Nothing removed automatically: the tree may be worth
  # keeping and re-running `npm ci` in. Just say how to undo it.
  cleanup_hint() {
    local code=$?
    [[ $code -eq 0 ]] && return 0
    {
      echo
      echo "✗ failed after the worktree was created. It is still on disk, holding slot ${slot}."
      echo "  Retry the install:  (cd $dir/backend && npm ci) && (cd $dir/frontend && npm ci)"
      echo "  Or remove it:       git -C $ROOT worktree remove --force $dir && git -C $ROOT branch -D $branch"
    } >&2
    return $code
  }
  trap cleanup_hint EXIT

  # Gitignored files a worktree does not inherit. These two are symlinked rather than copied so
  # the API key and the permission allowlist each keep exactly one source of truth. Relative
  # targets — an absolute one would break if the checkout were ever moved. `.claude/worktrees/` is
  # two levels below the root, so $dir needs ../../.. and a file one level inside it needs
  # ../../../.. to reach the root.
  # Collected rather than printed inline: they belong AFTER the npm ci output, next to the ✓, or
  # nobody sees them. A worktree missing either of these is not "ready" in any useful sense.
  local -a gaps=()

  if [[ -f "$ROOT/.env.shared" ]]; then
    ln -sfn "../../../.env.shared" "$dir/.env.shared"
  else
    gaps+=("no .env.shared in the main checkout, so this worktree has NO ANTHROPIC_API_KEY, no
    OIDC_* config and no sandbox limits — the generated .env carries slot identity only. Split
    your env first (cp .env.shared.example .env.shared, move the values across), then:
      ln -s ../../../.env.shared $dir/.env.shared")
  fi

  [[ -f "$ROOT/.claude/settings.local.json" ]] &&
    ln -sfn "../../../../.claude/settings.local.json" "$dir/.claude/settings.local.json"

  stack_env "$slot" "$project" >"$dir/.env"

  local auth0=""
  if [[ -f "$ROOT/frontend/.env.local" ]]; then
    # `|| true`: grep exits 1 on no match, and under `set -e` that would abort here — AFTER the
    # worktree and branch exist, leaving a half-built tree behind.
    auth0="$(grep -E '^VITE_AUTH0_' "$ROOT/frontend/.env.local" || true)"
  fi
  if [[ -z "$auth0" ]]; then
    gaps+=("no VITE_AUTH0_* values found in the main checkout's frontend/.env.local, so the SPA
    will start with an undefined Auth0 domain and client id and login will fail at runtime with
    no diagnostic. Fill in $ROOT/frontend/.env.local, then copy those three lines into
    $dir/frontend/.env.local")
  fi
  frontend_env "$slot" "$auth0" >"$dir/frontend/.env.local"

  (cd "$dir/backend" && npm ci)
  (cd "$dir/frontend" && npm ci)

  echo
  echo "✓ worktree ready: $dir"
  echo "  cd $dir && docker compose up --build"
  echo "  then open http://localhost:$(port_for "$BASE_FRONTEND" "$slot")"

  if ((${#gaps[@]} > 0)); then
    {
      echo
      echo "⚠ but it will not run yet:"
      local gap
      for gap in "${gaps[@]}"; do echo "  - $gap"; done
    } >&2
  fi
}

if [[ "${WORKTREE_NEW_LIB:-}" != "1" ]]; then
  main "$@"
fi
